#!/bin/sh -e
#
# rc.local
#
# This script is executed at the end of each multiuser runlevel.
# Make sure that the script will "exit 0" on success or any other
# value on error.
#
# In order to enable or disable this script just change the execution
# bits.
#
# By default this script does nothing.

# Print the IP address
_IP=$(hostname -I) || true
if [ "$_IP" ]; then
  printf "My IP address is %s\n" "$_IP"
fi

printf "starting raspy temp\n"
cd /home/pi/current/
su pi -c './start.sh >> /dev/null 2>&1 &'
#sudo ./start.sh &> /home/pi/log.log &

#cd /home/pi/current/
#su pi -c './start.sh >> /dev/null 2>&1 &'

#printf "starting lcd\n"
#sudo python /home/pi/tempToLCD.py &> /home/pi/py.log &

exit 0
